### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/angular-using-compile-link-readme#2]
There seems to be an image we are supposed to see here. May be a broken path?

<img width="646" alt="screen shot 2016-03-18 at 11 21 57 am" src="https://cloud.githubusercontent.com/assets/14326883/13875029/b94d9d04-ecfb-11e5-9cab-38d4b06c9410.png">

**Comment by aturkewi** [comment]
Thanks @onyoo. Looks like the markdown syntax was mixed up. Fixed this with PR #3
